#!/bin/bash
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

cp /home/zdev/.xinitrc /root/
cp /home/zdev/.Xdefaults /root/
cp /home/zdev/.mwmrc /root/

chmod +x /etc/rc.local
chown -R zdev /opt/s390